# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$sudo\
$nix_shell\
$all\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$fill\
$php\
$nodejs\
$ruby\
$rust\
$time\
$line_break\
$character\
"""
command_timeout = 2000
add_newline = true

[sudo]
format = '[ $symbol ]($style)'
symbol = ''
style = 'bold bg:yellow fg:black'
disabled = false

[fill]
symbol = '-'

[cmd_duration]
format = '[ $duration  ]($style)'
style = 'bg:yellow fg:black'

[os]
disabled = false
format = '[ $symbol ]($style)'
style = 'fg:black bg:white'

[directory]
truncation_length = 3
truncation_symbol = '…/'
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = 'bg:blue'
read_only_style = 'bg:blue'
read_only = ' '

[git_branch]
format = '[ $symbol $branch (:$remote_branch)]($style)'
style = 'fg:black bg:purple'
symbol = ''

[git_status]
format = '[$ahead_behind]($style)[$all_status]($style)'
style = 'fg:black bg:purple'
ahead = '⇡${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
behind = '⇣${count} '
untracked = '?${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '~${count} '
deleted = '-${count} '

[package]
symbol = ' '
disabled = true

[time]
disabled = false
format = '[ $time  ]($style)'
style = 'fg:black bg:white'

[nix_shell]
disabled = false
symbol = ''
style = 'bold bg:blue fg:white'

[directory.substitutions]
'~' = ''
'Dev' = ''
'Perso' = ''
'Documents' = ''
'Downloads' = ''
'Music' = ''
'Pictures' = ''

[aws]
symbol = '  '

[buf]
symbol = ' '

[c]
symbol = ' '

[conda]
symbol = ' '

[dart]
symbol = ' '

[docker_context]
symbol = ' '

[elixir]
symbol = ' '

[elm]
symbol = ' '

[golang]
symbol = ' '
format = '[ $symbol ($version) ]($style)'

[guix_shell]
symbol = ' '

[haskell]
symbol = ' '

[haxe]
symbol = '⌘ '

[hg_branch]
symbol = ' '

[java]
symbol = ' '

[julia]
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = ' '

[meson]
symbol = '喝 '

[nim]
symbol = ' '

[nodejs]
symbol = ''
format = '[ $symbol ($version) ]($style)'
style = 'bg:green fg:black bold'
version_format = 'v$major.$minor'

[php]
symbol = ''
format = '[ $symbol( $version) ]($style)'
style = 'bg:147 fg:black'
version_format = 'v$major.$minor'

[python]
symbol = ''

[rlang]
symbol = 'ﳒ'

[ruby]
symbol = ''
format = '[ $symbol( $version) ]($style)'
style = 'bg:red fg:white bold'
version_format = 'v$major.$minor'

[rust]
symbol = ''
format = '[ $symbol( $version) ]($style)'
style = 'bg:red fg:white bold'
version_format = 'v$major.$minor'

[scala]
symbol = ''

[spack]
symbol = '🅢'

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
DragonFly = ''
Emscripten = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = '﯑'
Gentoo = ''
HardenedBSD = 'ﲊ'
Illumos = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
MidnightBSD = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
openSUSE = ''
OracleLinux = ''
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Redox = ''
Solus = 'ﴱ'
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''
